kakao-tech-campus-3rd-step3/Team16_BE

- .gitignore
- build.gradle
- src/main/java/com/kakaotechcampus/team16be/Team16BeApplication.java
- src/main/java/com/kakaotechcampus/team16be/auth/client/KakaoAuthClient.java
- src/main/java/com/kakaotechcampus/team16be/auth/config/KakaoProperties.java
- src/main/java/com/kakaotechcampus/team16be/auth/config/RestTemplateConfig.java
- src/main/java/com/kakaotechcampus/team16be/auth/controller/AuthController.java
- src/main/java/com/kakaotechcampus/team16be/auth/dto/ErrorResponseDto.java
- src/main/java/com/kakaotechcampus/team16be/auth/dto/KakaoLoginResponse.java
- src/main/java/com/kakaotechcampus/team16be/auth/dto/KakaoTokenResponse.java
- src/main/java/com/kakaotechcampus/team16be/auth/dto/KakaoUserInfoResponse.java
- src/main/java/com/kakaotechcampus/team16be/auth/exception/AuthExceptionHandler.java
- src/main/java/com/kakaotechcampus/team16be/auth/exception/JwtErrorCode.java
- src/main/java/com/kakaotechcampus/team16be/auth/exception/JwtException.java
- src/main/java/com/kakaotechcampus/team16be/auth/exception/KakaoErrorCode.java
- src/main/java/com/kakaotechcampus/team16be/auth/exception/KakaoException.java
- src/main/java/com/kakaotechcampus/team16be/auth/jwt/JwtProvider.java
- src/main/java/com/kakaotechcampus/team16be/auth/service/KakaoAuthService.java
- src/main/java/com/kakaotechcampus/team16be/common/config/Webconfig.java
- src/main/java/com/kakaotechcampus/team16be/group/domain/SafetyTag.java
- src/main/java/com/kakaotechcampus/team16be/user/domain/Role.java
- src/main/java/com/kakaotechcampus/team16be/user/domain/User.java
- src/main/java/com/kakaotechcampus/team16be/user/domain/VerificationStatus.java
- src/main/java/com/kakaotechcampus/team16be/user/repository/UserRepository.java
- src/main/resources/application.properties
- Closes #5 
---
❗ 비즈앱 등록까지 해도 카카오 계정의 이름을 가져오는 건 사업자 등록 후 심사과정이 필요하다해서 실제 이름을 가져오는 로직은 구현에서 제외하였습니다. 
❗ 추가로 카카오 로그인 api는 프론트엔드와의 통신이 완료되었습니다.
❗  환경변수 .env 파일은 노출되면 안되는 파일로 gitignore 하여서 커밋되지 않은 상태이므로 따로 최상위 폴더 아래에 .env 파일을 추가하여 넣어주셔야 합니다.
> feat: 카카오 소셜 로그인 & 로그아웃 구현

- build.gradle
- src/main/java/com/kakaotechcampus/team16be/Team16BeApplication.java
- src/main/java/com/kakaotechcampus/team16be/aws/config/S3Config.java
- src/main/java/com/kakaotechcampus/team16be/aws/controller/ImageController.java
- src/main/java/com/kakaotechcampus/team16be/aws/domain/ImageFileExtension.java
- src/main/java/com/kakaotechcampus/team16be/aws/domain/ImageUploadType.java
- src/main/java/com/kakaotechcampus/team16be/aws/dto/ImageUrlDto.java
- src/main/java/com/kakaotechcampus/team16be/aws/dto/IssuePresignedUrlRequest.java
- src/main/java/com/kakaotechcampus/team16be/aws/service/S3UploadPresignedUrlService.java
- src/main/resources/application.properties
- close #15 
- 클라이언트는 서버에 pre-signed URL을 요청
- 서버에서 S3에 pre-signed URL을 요청
- S3는 pre-sigend URL을 서버에 반환
- 서버는 pre-signed URL을 클라이언트에 반환
- presgined-URL 발급은 중복되는 로직이기 때문에 태윤님과 같이 페어프로그래밍 했습니다
> feat: S3 presigned URL 발급해주는 api 구현

- src/main/java/com/kakaotechcampus/team16be/auth/client/KakaoAuthClient.java
- src/main/java/com/kakaotechcampus/team16be/auth/controller/AuthController.java
- src/main/java/com/kakaotechcampus/team16be/auth/exception/KakaoErrorCode.java
- src/main/java/com/kakaotechcampus/team16be/auth/jwt/JwtProvider.java
- src/main/java/com/kakaotechcampus/team16be/auth/service/KakaoAuthService.java
- src/main/resources/application.properties
- #25 
- 기존에 카카오 액세스 토큰과 만료시간을 동일하게 설정하는 로직을 제거하였고, jwt accessToken 만료시간을 따로 설정해주었습니다.
- 카카오 액세스 토큰을 세션에 저장하는 로직을 제거함에 따라 로그아웃 로직을 제거하였습니다. 이는 프론트에서 jwt를 단순 삭제하는 것으로 해결될 일이지만 추후에 블랙리스트를 적용해보려고 해서 빈 로직을 남겨두었습니다.
- 인가코드 받는 방식을 server-to-server로 변경함에 따라 로그인 api를 Post에서 Get으로 수정하였습니다.
> fix: 카카오 액세스 토큰을 세션에 저장하는 로직 제거 & 그에 따른 리팩토링

- src/main/java/com/kakaotechcampus/team16be/auth/controller/AuthController.java
- src/main/java/com/kakaotechcampus/team16be/aws/controller/ImageController.java
- src/main/java/com/kakaotechcampus/team16be/common/config/Webconfig.java
- close #27 
- @LoginUser 파라미터를 Long -> User로 변경하여 resolver와 호환되도록 수정하였습니다. (AuthController, ImageController 부분만 수정했으므로 다른 컨트롤러들도 수정해줘야할 필요가 있습니다)
- loginCheckInterceptor에서 로그인/로그아웃 API 제외하고 모든 요청 인증 체크하도록 수정하였습니다.
> fix: @LoginUser 타입 변경 및 loginCheckInterceptor 검증 범위 수정

- src/main/java/com/kakaotechcampus/team16be/auth/dto/UpdateStudentIdImageRequest.java
- src/main/java/com/kakaotechcampus/team16be/user/service/UserService.java
##before
```
{
"fileName": "users/1234/학생증_20250908.png",
"type": "VERIFICATION"
}
```
##after
```
{
"fileName": "users/1234/학생증_20250908.png"
}
```
현재 학생증 업로드 API(/student-verification)에서 요청 DTO가 아래와 같이 두 개의 필드를 받고 있습니다.
그러나
API가 목적별로 분리되어 있어, type 필드는 DB에 저장되지 않고 실제 서비스 로직에서도 사용되지 않습니다.
type 필드는 프론트에서 업로드 목적을 구분하기 위해 넣었던 안전장치였지만, 현재는 불필요한 상태입니다.
따라서 DTO의 type필드를 제거하였습니다.
> fix: UpdateStudentIdImageRequest의 type 필드 제거

- build.gradle
- src/main/java/com/kakaotechcampus/team16be/auth/controller/AdminAuthController.java
- src/main/java/com/kakaotechcampus/team16be/auth/controller/AuthController.java
- src/main/java/com/kakaotechcampus/team16be/aws/controller/ImageController.java
- src/main/java/com/kakaotechcampus/team16be/comment/controller/CommentController.java
- src/main/java/com/kakaotechcampus/team16be/common/config/Webconfig.java
- src/main/java/com/kakaotechcampus/team16be/groundrule/GroundRuleController.java
- src/main/java/com/kakaotechcampus/team16be/group/controller/GroupController.java
- src/main/java/com/kakaotechcampus/team16be/post/controller/PostController.java
- src/main/java/com/kakaotechcampus/team16be/report/controller/AdminReportController.java
- src/main/java/com/kakaotechcampus/team16be/report/controller/UserReportController.java
- src/main/java/com/kakaotechcampus/team16be/user/controller/UserController.java
- close #56 
- 프로젝트 전체 API에 Swagger 문서 적용
- Swagger 의존성 추가
- 불필요한 주석 제거
- Admin, 사용자 인증/인가, 신고 관리, 댓글, 모임, 게시글, 유저, 이미지 등 모든 컨트롤러에 Swagger 적용
- http://localhost:8080/swagger-ui.html 접속 후 API 문서 확인
- 앞으로  Operation과 Tag 어노테이션을 통해 api들을 swagger 문서화 할 수 있습니다
> feat: 현재 develop 브랜치의 모든 controller에 swagger 적용

- src/main/java/com/kakaotechcampus/team16be/common/config/SwaggerConfig.java
- close #72 
- Swagger UI에서 토큰 입력하고 API 테스트가 가능하도록 하기 위해 SwaggerConfig를 추가하고 설정을 해줬습니다.
> feat: Swagger UI에서 JWT 인증 테스트 가능하도록 설정

- src/main/java/com/kakaotechcampus/team16be/user/domain/User.java
- close #75  
- 디폴트 닉네임을 "익명"으로 설정
> fix: 사용자 프로필이미지 디폴트 값 설정

- src/main/java/com/kakaotechcampus/team16be/user/controller/UserController.java
- src/main/java/com/kakaotechcampus/team16be/user/service/UserService.java
- close #81 
- 계속 이슈가 있었는데 결론적으로 프론트랑 최종 논의한 결과
- delete시 null 반환
- defaultImage => null 반환
- 이렇게 수정하기로 함.
> fix: 프로필 이미지 처리 방법 최종 수정 (null)

- src/main/java/com/kakaotechcampus/team16be/user/service/UserService.java
- close #83 
- 기존에는 profileImageUrl이 null일 때 업데이트 시 USER-007 예외가 발생하였으나 제거하였습니다.
- profileImageUrl의 기본 디폴트 값을 null로 수정했기 때문입니다.
> fix: 프로필 이미지 업데이트 로직 수정

- src/main/java/com/kakaotechcampus/team16be/aws/controller/ImageController.java
- src/main/java/com/kakaotechcampus/team16be/aws/service/S3UploadPresignedUrlService.java
- src/main/java/com/kakaotechcampus/team16be/group/controller/GroupController.java
- src/main/java/com/kakaotechcampus/team16be/group/service/GroupService.java
- src/main/java/com/kakaotechcampus/team16be/group/service/GroupServiceImpl.java
1. 그룹 정보와 이미지 수정 로직 분리
그룹에 대한 정보와 이미지 수정을 분리시켰습니다. 
기존 코드 한 서비스에 너무나 많은 로직이 몰려있다는 것이 느껴져 분리시켜야겠다는 생각이 들었습니다.
2. S3 PresignedURL User / Group 분리
기존 로직을 살펴보니, Group 이미지가 각 UserId 별로 저장되어있다는 것이 확인되었습니다. 
그래서 S3서비스 계층에서 groupId를 전달 받아 groupId에 User가 해당 그룹의 그룹장 여부의 대한 로직을 추가하였고, 
이를 바탕으로 groupId에 대한 FileName을 생성하는 로직을 추가하였습니다.
3. ErrorCode 리팩토링
기존 작업중 develop을 pull 하여 충돌 해결할겸 ErrorCode를 리팩토링했습니다!
close #73
> fix: 그룹 정보와 이미지 설정 분리 및 S3 이미지 업로드 및 저장 로직 변경

- src/main/java/com/kakaotechcampus/team16be/comment/controller/CommentController.java
- src/main/java/com/kakaotechcampus/team16be/comment/domain/Comment.java
- src/main/java/com/kakaotechcampus/team16be/comment/dto/CommentIdResponse.java
- src/main/java/com/kakaotechcampus/team16be/comment/dto/CommentRequest.java
- src/main/java/com/kakaotechcampus/team16be/comment/dto/CommentResponse.java
- src/main/java/com/kakaotechcampus/team16be/comment/dto/CommentUpdateRequest.java
- src/main/java/com/kakaotechcampus/team16be/comment/dto/GetCommentsResponse.java
- src/main/java/com/kakaotechcampus/team16be/comment/exception/CommentErrorCode.java
- src/main/java/com/kakaotechcampus/team16be/comment/exception/CommentException.java
- src/main/java/com/kakaotechcampus/team16be/comment/repository/CommentRepository.java
- src/main/java/com/kakaotechcampus/team16be/comment/service/CommentService.java
- src/main/java/com/kakaotechcampus/team16be/comment/service/CommentServiceImpl.java
- close #87 
- 부모 댓글 작성(Create)
- 대댓글 작성(Create)
- 특정 게시글 댓글 전체 조회(Read)
- 댓글 수정(Update)
- 댓글 삭제(Delete)
- DTO(CommentRequest, CommentUpdateRequest, CommentResponse, CommentIdResponse) 활용
- @LoginUser를 통한 사용자 인증 정보 연동
- Swagger @Operation과 @Tag로 API 문서화
> feat: 게시글 댓글(Comment) CRUD 기능 구현 완료

- src/main/java/com/kakaotechcampus/team16be/attend/controller/AttendController.java
- src/main/java/com/kakaotechcampus/team16be/attend/controller/RequestAttendDto.java
- src/main/java/com/kakaotechcampus/team16be/attend/controller/ResponseAttendDto.java
- src/main/java/com/kakaotechcampus/team16be/attend/domain/Attend.java
- src/main/java/com/kakaotechcampus/team16be/attend/domain/AttendStatus.java
- src/main/java/com/kakaotechcampus/team16be/attend/repository/AttendRepository.java
- src/main/java/com/kakaotechcampus/team16be/attend/service/AttendService.java
- src/main/java/com/kakaotechcampus/team16be/attend/service/AttendServiceImpl.java
- src/main/java/com/kakaotechcampus/team16be/plan/service/PlanService.java
- src/main/java/com/kakaotechcampus/team16be/plan/service/PlanServiceImpl.java
- 도메인 설계
기존 DB설계를 조금 수정했습니다. 해당 사용자가 Group 가입 여부를 판단하는 것이 더욱 합리적이라고 생각하기에 User를 필드로 사용하는 것 보단, GroupMember를 필드로 사용하는 것을 채택했습니다. 또한
```
@Table(
uniqueConstraints = {
@UniqueConstraint(columnNames = {"plan_id", "group_member_id"})
}
)
```
를 추가하여 중복 출석을 방지했습니다.
- 출석 API
```
private AttendStatus checkAttendStatus(Plan plan) {
LocalDateTime now = LocalDateTime.now();
if (now.isBefore(plan.getStartTime())) {
return AttendStatus.PRESENT;
} else if (!now.isAfter(plan.getEndTime())) {
return AttendStatus.LATE;
} else {
return AttendStatus.ABSENT;
}
}
```
Plan에서의 시작 / 종료 시간을 요청하여 그에 따른 출석 여부를 판단했습니다
- close #90
> Feat(Attend): 일정 출석 API

- src/main/java/com/kakaotechcampus/team16be/plan/domain/Plan.java
- src/main/java/com/kakaotechcampus/team16be/plan/dto/PlanRequestDto.java
- src/main/java/com/kakaotechcampus/team16be/plan/dto/PlanResponseDto.java
- src/main/java/com/kakaotechcampus/team16be/plan/exception/PlanErrorCode.java
- src/main/java/com/kakaotechcampus/team16be/plan/service/PlanServiceImpl.java
- close #99 
1. 위도, 경도, 참여인원 수를 추가했습니다
-> 예외처리랑 에러코드도 추가해놨습니다.
참여인원수는 출석체크 기능과 연관되기 때문에
출석체크랑 연결되는 메소드들을 미리 추가해놔서 이거랑 연결지으면서 구현하면 될 것 같습니다.(increaseAttendee, decreaseAttendee)
API 명세서 및 에러코드 수정했습니다.
(https://www.notion.so/teamsparta/2442dc3ef51481a3afbdf4caa9bc0b87)
> refactor: plan 도메인에 위도,경도,참여인원 수 추가 및 관련 로직들 수정

- src/main/java/com/kakaotechcampus/team16be/auth/exception/JwtErrorCode.java
- src/main/java/com/kakaotechcampus/team16be/auth/exception/JwtException.java
- src/main/java/com/kakaotechcampus/team16be/auth/exception/KakaoErrorCode.java
- src/main/java/com/kakaotechcampus/team16be/auth/exception/KakaoException.java
- src/main/java/com/kakaotechcampus/team16be/comment/exception/CommentErrorCode.java
- src/main/java/com/kakaotechcampus/team16be/comment/exception/CommentException.java
- src/main/java/com/kakaotechcampus/team16be/common/exception/BaseException.java
- src/main/java/com/kakaotechcampus/team16be/common/exception/ErrorCode.java
- src/main/java/com/kakaotechcampus/team16be/common/exception/GlobalExceptionHandler.java
- src/main/java/com/kakaotechcampus/team16be/groundrule/exception/GroundRuleErrorCode.java
- src/main/java/com/kakaotechcampus/team16be/groundrule/exception/GroundRuleException.java
- src/main/java/com/kakaotechcampus/team16be/group/exception/GroupErrorCode.java
- src/main/java/com/kakaotechcampus/team16be/group/exception/GroupException.java
- src/main/java/com/kakaotechcampus/team16be/groupMember/exception/GroupMemberErrorCode.java
- src/main/java/com/kakaotechcampus/team16be/groupMember/exception/GroupMemberException.java
- src/main/java/com/kakaotechcampus/team16be/like/exception/LikeErrorCode.java
- src/main/java/com/kakaotechcampus/team16be/like/exception/LikeException.java
- src/main/java/com/kakaotechcampus/team16be/plan/exception/PlanErrorCode.java
- src/main/java/com/kakaotechcampus/team16be/plan/exception/PlanException.java
- src/main/java/com/kakaotechcampus/team16be/post/exception/PostErrorCode.java
- src/main/java/com/kakaotechcampus/team16be/post/exception/PostException.java
- src/main/java/com/kakaotechcampus/team16be/report/exception/ReportErrorCode.java
- src/main/java/com/kakaotechcampus/team16be/report/exception/ReportException.java
- src/main/java/com/kakaotechcampus/team16be/review/common/exception/ReviewErrorCode.java
- src/main/java/com/kakaotechcampus/team16be/review/common/exception/ReviewException.java
- src/main/java/com/kakaotechcampus/team16be/user/exception/UserErrorCode.java
- src/main/java/com/kakaotechcampus/team16be/user/exception/UserException.java
- close #108 
1. 모든 도메인 예외(BaseException 상속)
- JwtException, KakaoException, CommentException, GroundRuleException,
GroupException, GroupMemberException, LikeException, PlanException,
PostException, ReportException, ReviewException, UserException
- 공통 BaseException 상속
- ErrorCode(enum) 기반 메시지/코드/HTTP 상태 관리
2. 공통 ErrorCode 인터페이스 추가
- ErrorCode interface 생성
- getMessage()
- getCode()
- getStatus()
- 모든 도메인별 ErrorCode enum(UserErrorCode, PlanErrorCode, 등) implements ErrorCode
3. GlobalExceptionHandler 단일화
- @ExceptionHandler(BaseException.class) 단일 핸들러로 모든 예외 처리
- ResponseEntity<ErrorResponseDto> 반환
- JSON 구조: { message, code, status }
- 예외 구조 통합 → 중복 코드 제거
- 새로운 도메인 예외 추가 시 ErrorCode enum + Exception 클래스만 만들면 됨
- GlobalExceptionHandler 단일화로 유지보수 용이
이번 PR에서는 모든 도메인 예외를 BaseException 상속 + …
> refactor: 예외 통합 구조화 및 BaseException 적용

- src/main/java/com/kakaotechcampus/team16be/groupMember/controller/GroupMemberController.java
- src/main/java/com/kakaotechcampus/team16be/groupMember/domain/GroupMember.java
- src/main/java/com/kakaotechcampus/team16be/groupMember/dto/ApproveJoinRequestDto.java
- src/main/java/com/kakaotechcampus/team16be/groupMember/dto/BanMemberRequestDto.java
- src/main/java/com/kakaotechcampus/team16be/groupMember/dto/CancelSignRequestDto.java
- src/main/java/com/kakaotechcampus/team16be/groupMember/dto/ChangeLeaderRequestDto.java
- src/main/java/com/kakaotechcampus/team16be/groupMember/dto/JoinRequestDto.java
- src/main/java/com/kakaotechcampus/team16be/groupMember/dto/LeaveGroupRequestDto.java
- src/main/java/com/kakaotechcampus/team16be/groupMember/dto/RequestGroupMemberDto.java
- src/main/java/com/kakaotechcampus/team16be/groupMember/dto/SignGroupRequestDto.java
- src/main/java/com/kakaotechcampus/team16be/groupMember/dto/SignResponseDto.java
- src/main/java/com/kakaotechcampus/team16be/groupMember/repository/GroupMemberRepository.java
- src/main/java/com/kakaotechcampus/team16be/groupMember/service/GroupMemberFacade.java
- src/main/java/com/kakaotechcampus/team16be/groupMember/service/GroupMemberService.java
- src/main/java/com/kakaotechcampus/team16be/groupMember/service/GroupMemberServiceImpl.java
- src/main/java/com/kakaotechcampus/team16be/notification/controller/NotificationController.java
- src/main/java/com/kakaotechcampus/team16be/notification/domain/Notification.java
- src/main/java/com/kakaotechcampus/team16be/notification/domain/NotificationType.java
- src/main/java/com/kakaotechcampus/team16be/notification/dto/ResponseNotification.java
- src/main/java/com/kakaotechcampus/team16be/notification/exception/NotificationErrorCode.java
- src/main/java/com/kakaotechcampus/team16be/notification/exception/NotificationException.java
- src/main/java/com/kakaotechcampus/team16be/notification/repository/EmitterRepository.java
- src/main/java/com/kakaotechcampus/team16be/notification/repository/NotificationRepository.java
- src/main/java/com/kakaotechcampus/team16be/notification/service/NotificationService.java
- src/main/java/com/kakaotechcampus/team16be/notification/service/NotificationServiceImpl.java
- src/main/java/com/kakaotechcampus/team16be/plan/domain/Plan.java
- src/main/java/com/kakaotechcampus/team16be/plan/service/PlanServiceImpl.java
- close #120 
- 1. EmitterRepository에서 해당 유저의 SseEmitter를 가져옴
- 2. SseEmitter.send()를 통해 클라이언트로 이벤트 전송
- 3. 전송 실패 시 해당 SseEmitter 삭제 후 예외 처리
- 4. 결과: 클라이언트에서는 SSE 구독 중인 이벤트를 받아 "새로운 알림이 도착했습니다." 같은 데이터를 실시간으로 표시
- GROUP_JOIN_REQUEST → 가입 신청
- GROUP_MEMBER_WITHDRAWAL → 모임 유저가 그룹에서 탈퇴
- 가입 신청 → createGroupJoinRequestNotification → 그룹장에게 알림
- 가입 승인 완료 → createGroupJoinNotification → 신청한 유저에게 알림
- 탈퇴 → createGroupMemberWithdrawalNotification → 그룹장에게 알림
- 강퇴 → createGroupMemberBannedNotification → 강퇴당한 유저에게 알림
- 가입 신청 취소 → createGroupJoinRequestCancelNotification → 그룹장에게 알림
- 그룹장용 – 가입신청 알림 조회 -> 목적: 아직 처리 안 한 가입 요청 리스트 보여주기
- 일반 유저용 – 전체 알림 조회 -> 목적: 가입 승인, 댓글, 메시지 등 모든 알림 확인
> feat: SSE 환경 구축 & 알림 도메인 구현 및 적용

- src/main/java/com/kakaotechcampus/team16be/post/controller/PostController.java
- src/main/java/com/kakaotechcampus/team16be/post/dto/GetPostResponse.java
- src/main/java/com/kakaotechcampus/team16be/post/service/PostService.java
- src/main/java/com/kakaotechcampus/team16be/post/service/PostServiceImpl.java
게시글 조회 API 응답에 다음 정보가 추가되면 좋겠습니다:
- 댓글 개수
- 좋아요 수
- 현재 사용자가 해당 게시글에 좋아요를 눌렀는지 여부
- 프론트엔드에서 별도의 API 호출 없이 한 번에 필요한 데이터를 받을 수 있습니다.
- 사용자 경험(UX) 개선 및 API 호출 횟수 감소로 성능 최적화에 도움이 됩니다.
- 게시글 조회 시 댓글 개수, 좋아요 수, 좋아요 여부를 함께 반환하도록 응답 DTO 및 관련 컨트롤러 & 서비스 로직 수정
> fix: 게시글 조회 응답 데이터 확장 (댓글 수/좋아요 수/좋아요 여부)

- src/main/java/com/kakaotechcampus/team16be/common/exception/GlobalExceptionHandler.java
- close #142 
- GlobalExceptionHandler에 @ExceptionHandler(Exception.class) 추가
- 예상치 못한 예외(NullPointerException 등)도 일관된 응답 포맷으로 반환
- Slf4j 로깅 적용
- 운영 환경에서도 예외 로그가 안전하게 남도록 개선
- BaseException 외의 시스템 예외도 클라이언트에 표준화된 에러 응답을 제공하기 위함
- 로깅을 통해 장애 상황을 추적 가능하게 하여 안정성 확보
- 에러 응답 포맷: ErrorResponseDto(message, code, status)
- UNEXPECTED_ERROR 코드로 처리
> feat: 전역 예외 처리에 Unexpected Exception 핸들링 추가 및 로깅 설정

- build.gradle
- src/main/java/com/kakaotechcampus/team16be/chatroom/controller/ChatRoomController.java
- src/main/java/com/kakaotechcampus/team16be/chatroom/domain/ChatRoom.java
- src/main/java/com/kakaotechcampus/team16be/chatroom/domain/ChatRoomMessage.java
- src/main/java/com/kakaotechcampus/team16be/chatroom/domain/ChatRoomUser.java
- src/main/java/com/kakaotechcampus/team16be/chatroom/dto/CreateChatRoomDto.java
- src/main/java/com/kakaotechcampus/team16be/chatroom/dto/ResponseChatRoomDto.java
- src/main/java/com/kakaotechcampus/team16be/chatroom/dto/UpdateChatRoomDto.java
- src/main/java/com/kakaotechcampus/team16be/chatroom/exception/ChatRoomErrorCode.java
- src/main/java/com/kakaotechcampus/team16be/chatroom/exception/ChatRoomException.java
- src/main/java/com/kakaotechcampus/team16be/chatroom/repository/ChatRoomRepository.java
- src/main/java/com/kakaotechcampus/team16be/chatroom/service/ChatRoomService.java
- src/main/java/com/kakaotechcampus/team16be/chatroom/service/ChatRoomServiceImpl.java
- src/main/java/com/kakaotechcampus/team16be/common/config/WebSocketConfig.java
- close #165 
- **ChatRoom**: 채팅방 엔티티, ID, 이름, 그룹, 참여자 관리, 생성/수정/그룹 검증 메서드 포함
- **ChatRoomUser**: 채팅방 참여자 엔티티, ChatRoom ↔ User 다대다 관계 매핑
- **ChatRoomMessage**: 채팅 메시지 엔티티, 채팅방, 메시지 내용, 작성자 연관관계 포함
- **ResponseChatRoomDto**: ChatRoom → API 응답 변환
- **CreateChatRoomDto**: 채팅방 생성 요청 DTO
- **UpdateChatRoomDto**: 채팅방 이름 수정 요청 DTO
- **ChatRoomRepository**: 그룹별 채팅방 조회 메서드(`findChatRoomsByGroup`) 제공
- **ChatRoomService** 인터페이스: 채팅방 CRUD 메서드 정의
- **ChatRoomServiceImpl**: CRUD 로직 구현, 권한 체크 포함
- **ChatRoomController**: REST API 제공 (`GET/POST/PUT/DELETE /api/group/{groupId}/chat`), DTO 변환 후 JSON 응답
- **WebSocketConfig**: `/ws` 엔드포인트 등록, 브로커 설정(`/topic`, `/queue`), 클라이언트 메시지 접두사 `/app`, SockJS 지원
- **동작 흐름**
1. 클라이언트가 `/ws`로 STOMP 연결
2. 클라이언트가 `/topic/chat/{roomId}` 구독
3. 클라이언트가 `/app/chat/message` 전송 …
> feat: 채팅방 CRUD 구현 및 실시간 메시지 기능 구현을 위한 WebSocket 설정 및 ChatRoomMessage 엔티티 미리 정의

- src/main/java/com/kakaotechcampus/team16be/auth/client/KakaoAuthClient.java
- src/main/java/com/kakaotechcampus/team16be/auth/controller/AuthController.java
- src/main/java/com/kakaotechcampus/team16be/auth/exception/KakaoErrorCode.java
- src/main/java/com/kakaotechcampus/team16be/auth/service/KakaoAuthService.java
- close #172 
- requestAccessToken() 메서드에서 Kakao 토큰 요청 실패 시 발생할 수 있는 모든 경우를 세분화
- HTTP 상태 코드 비정상: TOKEN_REQUEST_FAILED_HTTP_STATUS
- 응답 body null: TOKEN_REQUEST_FAILED_NULL_BODY
- access_token 누락: TOKEN_REQUEST_FAILED_NO_TOKEN
- 클라이언트 에러: TOKEN_REQUEST_FAILED_CLIENT
- 서버 에러: TOKEN_REQUEST_FAILED_SERVER
- Kakao 서버 연결 실패: CONNECTION_FAILED
- 그 외 알 수 없는 예외: UNKNOWN_ERROR
- 각 경우별로 상세 로그 출력 추가
- KakaoException에 Throwable 포함 생성자 추가로 원인 추적 가능
- 배포 환경에서 Kakao 로그인 실패 원인 파악 용이
- 배포 환경에서 Kakao 로그인 실패 시 원인을 빠르게 파악 가능
- 서버 로그를 통해 어떤 단계에서 문제가 발생했는지 확인 가능
> refactor: Kakao 토큰 요청 예외 세분화 및 상세 로그 추가

- src/main/java/com/kakaotechcampus/team16be/auth/client/KakaoAuthClient.java
- src/main/java/com/kakaotechcampus/team16be/auth/exception/KakaoErrorCode.java
- close #174 
- 기존에는 Kakao 토큰 요청 실패 시 클라이언트 에러가 발생하면 무조건 TOKEN_REQUEST_FAILED_CLIENT 예외만 던졌음
- 개선:
- 응답 body 분석 후 세부 원인에 따라 다른 예외 처리
- invalid_grant → INVALID_AUTHORIZATION_CODE
- invalid_client → INVALID_CLIENT_ID
- 그 외 클라이언트 에러 → TOKEN_REQUEST_FAILED_CLIENT
- 로그에 응답 body 출력 추가로 문제 원인 파악 용이
> feat: HttpClientErrorException 에러 처리 세분화

- src/main/java/com/kakaotechcampus/team16be/auth/client/KakaoAuthClient.java
- close #178 
- 카카오 로그인 시 인가 코드(`code`) 전달 과정에서 발생할 수 있는
invalid_grant 오류를 방지하기 위해 처리 로직 개선
1. code.trim() 추가: 전달된 인가 코드의 앞뒤 공백 제거
2. URLDecoder.decode(code, UTF-8) 추가: URL 인코딩된 문자 정상 처리
- 배포 환경에서 인가 코드 요청 시 `AUTH_CODE_INVALID` 또는 `invalid_grant` 발생
- 로컬 환경에서는 문제가 없었음
> fix: 카카오 인가 코드 처리 시 공백 및 URL 디코딩 적용

- src/main/java/com/kakaotechcampus/team16be/auth/client/KakaoAuthClient.java
- close #180 
- Kakao 토큰 요청 중 `invalid_grant` 관련 에러 처리 로직 개선
- `responseBody`를 소문자로 변환 후 검사하여 대소문자 차이로 조건이 누락되는 문제 해결
- redirect URI 불일치(`redirect_uri mismatch`) 에러가 정확히 `KakaoErrorCode.REDIRECT_URI_MISMATCH`로 매핑되도록 수정
- `KakaoAuthClient`의 `HttpClientErrorException` 처리 로직에서 `responseBody.toLowerCase()` 적용
- 기존 if-else 조건 구조 유지하며, 소문자 변환으로 모든 에러 케이스 정확히 감지
- 카카오 로그인 중 redirect URI 불일치 에러가 정확하게 감지됨
- `AUTH_CODE_INVALID`로 잘못 처리되는 문제 방지
> fix: Kakao 로그인 HttpClientErrorException 처리 시 responseBody 소문자 변환 후 검사

- .github/workflows/deploy.yml
- close #182 
- EC2에서 애플리케이션 실행 시 필요한 환경변수(DB, JWT, Kakao, AWS 등)를 SSH 스크립트에서 주입하도록 수정
- 기존 배포/실행 로직은 변경하지 않고, 환경변수 주입만 추가
- GitHub Actions Secrets를 사용하여 안전하게 값 관리
- Deploy and Run on EC2 단계 SSH 스크립트에 환경변수 `export` 추가
- 배포 시 Spring Boot가 Secrets 기반 환경변수를 참조 가능하도록 설정
> feat: EC2 배포 SSH 스크립트 deploy.yml에 환경변수 주입 추가

- src/main/java/com/kakaotechcampus/team16be/group/controller/GroupController.java
- src/main/java/com/kakaotechcampus/team16be/group/dto/ResponseSingleGroupDto.java
- close #188 
프론트엔드 요청에 따라 모임 상세 조회 API 응답에 createdAt(생성일)과 capacity(정원) 필드를 추가했습니다.
Group 엔티티에 해당 데이터가 이미 존재하므로, DTO(ResponseSingleGroupDto) 확장만으로 처리했습니다.
- ResponseSingleGroupDto
- LocalDateTime createdAt 필드 추가
- int capacity 필드 추가
- from() 메서드 내 group.getCreatedAt(), group.getCapacity() 반환 추가
- 서비스(getGroup) 로직 변경 없음 (DTO 내부 처리)
> feat: 그룹 상세 조회 API 반환값에 createdAt, capacity 필드 추가

- src/main/resources/application.properties
- 1. close #145 
- 2. close #171 
1. `GroupMemberDto.from()` 메서드에서 `member.getGroup().getName()`과 `member.getUser().getNickname()` 호출 시 N+1 쿼리 발생
- GroupMember 엔티티에서 Group과 User가 `@ManyToOne(fetch = LAZY)`로 설정되어 있어,  
Repository에서 멤버 리스트 조회 후 DTO 변환 시점에 각각 별도의 쿼리 발생
- 예시: 멤버 10명 기준 → 총 1 + (10*2) = 21번 쿼리 발생
- 작은 데이터에서는 문제가 크지 않지만, 멤버 수가 많아지면 DB 부하 및 성능 저하 발생
2. `CommentFacadeService.getCommentsByPostId` 메서드에서 Post와 연관된 Comment 조회 시 N+1 쿼리 발생 가능
- Post 1개 조회 → 1쿼리
- 해당 Post의 Comment 10개 조회 → 각 Comment마다 추가 쿼리 발생  
→ 총 11번 이상의 쿼리 발생 가능
- JPA Lazy Loading으로 인해 성능 저하와 서버 부하 발생 가능
- `spring.jpa.properties.hibernate.default_batch_fetch_size=50` 전역 설정 적용
- Hibernate가 LAZY 관계를 **한 번에 50개씩 묶어서 조회**하도록 설정
- 엔티티 단위 `@BatchSize` 제거하여 전역 설정으로 통일
- N+1 문제가 발생할 수 있는 GroupMember, Comment 등 모든 LAZY 관계에서 …
> chore: Hibernate 전역 Batch Fetch Size 50으로 설정하여 N+1 문제 완화

- src/main/java/com/kakaotechcampus/team16be/common/exception/GlobalExceptionHandler.java
- src/main/java/com/kakaotechcampus/team16be/groupMember/repository/GroupMemberRepository.java
- src/main/java/com/kakaotechcampus/team16be/user/controller/UserController.java
- src/main/java/com/kakaotechcampus/team16be/user/service/UserService.java
- close #197 
- 기존 /api/users/me, /api/users/history 엔드포인트를 PathVariable로 userId를 받는 구조로 변경하였습니다.
- 이제 어떤 사용자든 /api/users/{userId}, /api/users/{userId}/history로 조회 가능합니다.
- 다른 사람의 마이페이지나 히스토리를 조회해야할 필요가 있기 때문입니다. 기존엔 로그인한 사용자 본인꺼만 조회가 가능했습니다.
- 별도의 /api/users/{userId} API를 새로 만드는 대신, 기존 /me 구조를 확장하는 편이 유지보수성 측면에서 더 효율적입니다.
- GlobalExceptionHandler에서 발생한 모든 예외 메시지를 직접 반환하도록 수정하였습니다.  
- 기존에는 잘못된 API 경로로 요청할 경우 "예상치 못한 서버 오류"만 표시되어 원인 파악이 어려웠습니다.  
- 따라서 NoHandlerFoundException과 같은 예상치 못한 오류의 경우에도 실제 예외 메시지를 클라이언트에 직접 반환하도록 개선하였습니다.
- url 잘못 입력했을 경우
- 메소드 잘못 입력했을 경우
> fix: 사용자 마이페이지 조회 API들을 userId 기반 조회로 변경
